# Generated by Django 4.2.18 on 2025-01-26 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AUTHENTICATE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brother_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EXEC', 'Executive Board'), ('PLEDGE_BOARD', 'Pledge Board'), ('ACTIVE', 'Active Member'), ('ALUMNI', 'Alumni'), ('NEW_MEMBER', 'New Member'), ('SOCIAL_CHAIR', 'Social Chair'), ('RUSH_CHAIR', 'Rush Chair')], max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='brother_profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='AUTHENTICATE.role'),
        ),
        migrations.AddField(
            model_name='brother_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
