# Generated by Django 5.1.5 on 2025-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0002_brother_profile_role_delete_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brother_profile",
            name="profileImage",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
