# Generated by Django 5.1.5 on 2025-01-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0003_brother_profile_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brother_profile",
            name="profileImage",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
