# Generated by Django 5.1.5 on 2025-01-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0004_alter_brother_profile_profileimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="brother_profile",
            name="majors",
            field=models.ManyToManyField(blank=True, to="AUTHENTICATE.major"),
        ),
    ]
