# Generated by Django 5.1.5 on 2025-01-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0005_major_brother_profile_majors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(
                choices=[
                    ("Biological Engineering", "Biological Engineering"),
                    ("Biomedical Engineering", "Biomedical Engineering"),
                    ("Chemical Engineering", "Chemical Engineering"),
                    ("Civil Engineering", "Civil Engineering"),
                    ("Computer Engineering", "Computer Engineering"),
                    ("Computer Science", "Computer Science"),
                    ("Data Science", "Data Science"),
                    ("Electrical Engineering", "Electrical Engineering"),
                    ("Environmental Engineering", "Environmental Engineering"),
                    ("Industrial Engineering", "Industrial Engineering"),
                    ("Information Technology", "Information Technology"),
                    ("Mechanical Engineering", "Mechanical Engineering"),
                    ("Other", "Other"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
