# Generated by Django 5.1.5 on 2025-02-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0006_alter_major_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brother_profile",
            name="profileImage",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
