# Generated by Django 4.2.16 on 2025-02-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0007_alter_brother_profile_profileimage_alter_major_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('EXEC', 'Executive Board'), ('PLEDGE_BOARD', 'Pledge Board'), ('ACTIVE', 'Active Member'), ('ALUMNI', 'Alumni'), ('NEW_MEMBER', 'New Member'), ('SOCIAL_CHAIR', 'Social Chair'), ('RUSH_CHAIR', 'Rush Chair'), ('PHIL_CHAIR', 'Philanthropy Chair')], max_length=50, unique=True),
        ),
    ]
