# Generated by Django 4.2.16 on 2025-02-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0008_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('EXEC', 'Executive Board'), ('NM_BOARD', 'New Member Board'), ('ACTIVE', 'Active Member'), ('ALUMNI', 'Alumni'), ('NEW_MEMBER', 'New Member'), ('SOCIAL_CHAIR', 'Social Chair'), ('RUSH_CHAIR', 'Rush Chair'), ('PHIL_CHAIR', 'Philanthropy Chair')], max_length=50, unique=True),
        ),
    ]
