# Generated by Django 4.2.18 on 2025-03-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0009_alter_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="brother_profile",
            name="hometown",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
