# Generated by Django 4.2.18 on 2025-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0010_brother_profile_hometown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brother_profile",
            name="profileImage",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
