# Generated by Django 4.2.18 on 2025-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AUTHENTICATE", "0011_alter_brother_profile_profileimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brother_profile",
            name="dateCreated",
        ),
        migrations.AddField(
            model_name="brother_profile",
            name="pclass",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="brother_profile",
            name="roles",
            field=models.ManyToManyField(to="AUTHENTICATE.role"),
        ),
    ]
