# Generated by Django 5.1.9 on 2025-05-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0012_remove_brother_profile_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('EXEC', 'Executive Board'), ('NM_BOARD', 'New Member Board'), ('ACTIVE', 'Active Member'), ('ALUMNI', 'Alumni'), ('NEW_MEMBER', 'New Member'), ('SOCIAL_CHAIR', 'Social Chair'), ('RECRUITMENT_CHAIR', 'Recruitment Chair'), ('PHIL_CHAIR', 'Philanthropy Chair')], max_length=50, unique=True),
        ),
    ]
