# Generated by Django 5.1.13 on 2025-11-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0014_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text to display on the button', max_length=200)),
                ('link', models.URLField(help_text='URL for the button')),
            ],
        ),
    ]
