# Generated by Django 4.2.18 on 2025-11-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0015_dashboardlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardlink',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dashboardlink',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
