# Generated by Django 4.2.18 on 2025-11-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0016_alter_dashboardlink_options_dashboardlink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlink',
            name='link',
            field=models.CharField(help_text='URL for the button', max_length=200),
        ),
    ]
