# Generated by Django 4.2.18 on 2025-11-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0017_alter_dashboardlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother_profile',
            name='pclass',
            field=models.CharField(blank=True, choices=[('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Gamma', 'Gamma'), ('Delta', 'Delta'), ('Epsilon', 'Epsilon'), ('Zeta', 'Zeta'), ('Eta', 'Eta'), ('Theta', 'Theta'), ('Iota', 'Iota'), ('Kappa', 'Kappa'), ('Lambda', 'Lambda'), ('Mu', 'Mu'), ('Nu', 'Nu'), ('Xi', 'Xi'), ('Omicron', 'Omicron'), ('Pi', 'Pi'), ('Rho', 'Rho'), ('Sigma', 'Sigma'), ('Tau', 'Tau'), ('Upsilon', 'Upsilon'), ('Phi', 'Phi'), ('Chi', 'Chi'), ('Psi', 'Psi'), ('Omega', 'Omega'), ('Beta Alpha', 'Beta Alpha'), ('Beta Beta', 'Beta Beta'), ('Beta Gamma', 'Beta Gamma'), ('Beta Delta', 'Beta Delta'), ('Beta Epsilon', 'Beta Epsilon'), ('Beta Zeta', 'Beta Zeta'), ('Beta Eta', 'Beta Eta'), ('Beta Theta', 'Beta Theta'), ('Beta Iota', 'Beta Iota'), ('Beta Kappa', 'Beta Kappa'), ('Beta Lambda', 'Beta Lambda'), ('Beta Mu', 'Beta Mu'), ('Beta Nu', 'Beta Nu'), ('Beta Xi', 'Beta Xi'), ('Beta Omicron', 'Beta Omicron'), ('Beta Pi', 'Beta Pi'), ('Beta Rho', 'Beta Rho'), ('Beta Sigma', 'Beta Sigma'), ('Beta Tau', 'Beta Tau'), ('Beta Upsilon', 'Beta Upsilon'), ('Beta Phi', 'Beta Phi'), ('Beta Chi', 'Beta Chi'), ('Beta Psi', 'Beta Psi'), ('Beta Omega', 'Beta Omega')], max_length=50, null=True),
        ),
    ]
