# Generated by Django 4.2.18 on 2026-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATE', '0019_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('EXEC', 'Executive Board'), ('NM_BOARD', 'New Member Board'), ('ACTIVE', 'Active Member'), ('ALUMNI', 'Alumni'), ('NEW_MEMBER', 'New Member'), ('SOCIAL_CHAIR', 'Social Chair'), ('RECRUITMENT_CHAIR', 'Recruitment Chair'), ('PHIL_CHAIR', 'Philanthropy Chair'), ('RISK_MGR', 'Risk Manager'), ('PREV_RISK_MGR', 'Previous Risk Manager'), ('PRESIDENT', 'President'), ('INT_VP', 'Internal VP'), ('EXT_VP', 'External VP'), ('BUSINESS_MGR', 'Business Manager'), ('AFFAIRS_DIRECTOR', 'Director of Chapter Affairs'), ('NME', 'New Member Educator')], max_length=50, unique=True),
        ),
    ]
