# Generated by Django 5.1.13 on 2025-11-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the banner', max_length=200, null=True)),
                ('image', models.ImageField(help_text='Upload a new banner image', upload_to='banners/')),
            ],
        ),
    ]
