# Generated by Django 5.1.13 on 2025-11-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(blank=True, help_text='Name of Class', max_length=200, null=True),
        ),
    ]
