# Generated by Django 5.1.13 on 2025-11-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_alter_bannerimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='title',
        ),
    ]
