# Generated by Django 5.1.13 on 2025-11-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_remove_bannerimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RushFormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='URL for the Rush Interest Form')),
            ],
        ),
    ]
