# Generated by Django 4.2.18 on 2025-11-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_rushformlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='RushSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a slide image', upload_to='rush_slides/')),
                ('caption', models.CharField(help_text='Caption for the slide', max_length=200)),
                ('order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
