# Generated by Django 6.1.1 on 2026-09-28 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sober_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(help_text='Name of the event', max_length=100)),
                ('event_date', models.DateField(help_text='The date of the event')),
                ('duty_type', models.CharField(choices=[('MONITOR', 'Sober Monitor'), ('DRIVER', 'Sober Driver')], max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_sobersheet_duties', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobersheet_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sober Duty',
                'verbose_name_plural': 'Sober Duties',
                'ordering': ['-event_date'],
            },
        ),
    ]
