# Generated by Django 6.1.1 on 2026-09-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOBERSHEET', '0002_sober_exemption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sober_exemption',
            options={'verbose_name': 'Sober Exemption', 'verbose_name_plural': 'Sober Exemptions'},
        ),
    ]
