# Generated by Django 4.2.16 on 2025-02-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHILANTHROPY', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philanthropy_hours_event_and_request',
            name='philanthropy_event_name',
        ),
    ]
