# Generated by Django 5.1.12 on 2025-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHILANTHROPY', '0002_remove_philanthropy_hours_event_and_request_philanthropy_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philanthropy_hours_event_and_request',
            name='philanthropy_approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('requested', 'Requested'), ('denied', 'Denied')], default='requested', help_text='Event status: approved, requested, or denied', max_length=20),
        ),
        migrations.AlterField(
            model_name='philanthropy_hours_event_and_request',
            name='philanthropy_event_approver_name',
            field=models.CharField(blank=True, help_text='The name of the person who approved/denied the event', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='philanthropy_hours_event_and_request',
            name='philanthropy_event_submission_approval_date',
            field=models.DateTimeField(blank=True, help_text='The date the event was approved/denied', null=True),
        ),
        migrations.AlterField(
            model_name='philanthropy_hours_event_and_request',
            name='philanthropy_event_submission_request_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the event was submitted'),
        ),
        migrations.AlterField(
            model_name='philanthropy_hours_event_and_request',
            name='philanthropy_event_title',
            field=models.CharField(help_text='Short description of the event', max_length=100),
        ),
    ]
