# Generated by Django 5.1.13 on 2025-11-07 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHILANTHROPY', '0003_alter_philanthropy_hours_event_and_request_philanthropy_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='philanthropy_hours_event_and_request',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='philanthropy_hours_event_and_request',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_philanthropy_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
