# Generated by Django 5.1.5 on 2025-01-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayLightSavingsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Dashboard Annoucement Alert Settings',
                'verbose_name_plural': 'Dashboard Annoucement Alert Settings',
            },
        ),
    ]
