# Generated by Django 5.1.5 on 2025-02-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MISC", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="daylightsavingsalert",
            options={
                "verbose_name": "Day Light Savings Button Settings",
                "verbose_name_plural": "Day Light Savings Button Settings",
            },
        ),
    ]
