# Generated by Django 5.1.5 on 2025-01-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MISC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daylightsavingsalert',
            old_name='custom_alert',
            new_name='name',
        ),
    ]
