# Generated by Django 5.1.5 on 2025-02-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='daylightsavingsalert',
            options={'verbose_name': 'Day Light Savings Button Settings', 'verbose_name_plural': 'Day Light Savings Button Settings'},
        ),
    ]
