# Generated by Django 4.2.16 on 2025-02-02 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMember_Mark_Event_and_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_event_title', models.CharField(help_text='reason for the mark', max_length=100)),
                ('mark_approval_status', models.CharField(choices=[('approved', 'Approved'), ('requested', 'Requested'), ('denied', 'Denied')], default='requested', help_text='choice between approved, requested, and denied', max_length=20)),
                ('mark_value', models.IntegerField(help_text='Can be positive or negative')),
                ('mark_event_date', models.DateField(help_text='The date the mark was issued')),
                ('mark_submission_request_date', models.DateTimeField(auto_now_add=True, help_text='When the mark is submitted this updates')),
                ('mark_submission_approval_date', models.DateTimeField(blank=True, help_text='When the mark is approved this updates', null=True)),
                ('mark_approver_name', models.CharField(blank=True, help_text='This is the name of the person who approved the mark', max_length=100, null=True)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_requests_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'New Member Mark Event',
                'verbose_name_plural': 'New Member Mark Events',
                'ordering': ['-mark_event_date'],
            },
        ),
    ]
