# Generated by Django 4.2.16 on 2025-02-02 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NEWMEMBER', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember_mark_event_and_request',
            name='requesting_user',
            field=models.ForeignKey(help_text='The active member submitting the mark', on_delete=django.db.models.deletion.CASCADE, related_name='mark_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newmember_mark_event_and_request',
            name='target_user',
            field=models.ForeignKey(help_text='The new member receiving the mark', on_delete=django.db.models.deletion.CASCADE, related_name='marks_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
