# Generated by Django 5.1.12 on 2025-10-02 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWMEMBER', '0002_alter_newmember_mark_event_and_request_requesting_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember_mark_event_and_request',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newmember_mark_event_and_request',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newmember_mark_event_and_request',
            name='mark_approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('requested', 'Requested'), ('denied', 'Denied')], default='requested', help_text='Mark Status: approved, requested, or denied', max_length=20),
        ),
        migrations.AlterField(
            model_name='newmember_mark_event_and_request',
            name='mark_approver_name',
            field=models.CharField(blank=True, help_text='The name of the person who approved/denied the mark', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newmember_mark_event_and_request',
            name='mark_submission_approval_date',
            field=models.DateTimeField(blank=True, help_text='The date the mark was approved/denied', null=True),
        ),
        migrations.AlterField(
            model_name='newmember_mark_event_and_request',
            name='mark_submission_request_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the mark was submitted'),
        ),
    ]
