# Generated by Django 4.2.18 on 2025-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vote_name', models.CharField(blank=True, max_length=200, null=True)),
                ('No_votes', models.IntegerField(default=0, max_length=1000, null=True)),
                ('Yes_votes', models.IntegerField(default=0, max_length=1000, null=True)),
            ],
        ),
    ]
