# Generated by Django 4.2.18 on 2025-01-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARLEYPRO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_tracker',
            name='No_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vote_tracker',
            name='Yes_votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
