# Generated by Django 4.2.18 on 2025-01-25 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PARLEYPRO', '0002_alter_vote_tracker_no_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brother_votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_choice', models.CharField(choices=[('Aye', 'Aye'), ('Nay', 'Nay')], max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Vote_Tracker',
        ),
    ]
