# Generated by Django 4.2.18 on 2025-01-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARLEYPRO', '0003_brother_votes_delete_vote_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brother_votes',
            name='vote_choice',
        ),
        migrations.AddField(
            model_name='brother_votes',
            name='user_vote_choice',
            field=models.CharField(choices=[('Aye', 'Aye'), ('Nay', 'Nay'), ('No Vote', 'No Vote')], max_length=200, null=True),
        ),
    ]
