# Generated by Django 4.2.18 on 2025-01-26 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PARLEYPRO', '0004_remove_brother_votes_vote_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vote_Poll_Name', models.CharField(max_length=200, null=True)),
                ('Vote_Poll_Start', models.DateTimeField(auto_now_add=True)),
                ('Vote_Poll_Count_Yes', models.IntegerField(blank=True, default=0, null=True)),
                ('Vote_Poll_Count_No', models.IntegerField(blank=True, default=0, null=True)),
                ('Vote_Poll_End', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
